services:
  server:
    build:
      context: .
      target: development
    environment:
      NODE_ENV: development
      DATABASE_URL: mongodb://db:27017/pick-a-nest-db
      DATABASE_NAME: pick-a-nest-db
      REDIS_URL: redis://redis:6379
      SECRET: ${SECRET}
      REFRESH_EXPIRES_IN: 30d
      ACCESS_EXPIRES_IN: 45m
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  redis:
    image: redis:8.8-m03-trixie
    ports:
      - '6379:6379'
  db:
    image: mongo:8.0.20
    ports:
      - 27017:27017
    volumes:
      - real_estate:/data/db

volumes:
  real_estate:
