services:
  server:
    build:
      context: .
      target: development
    environment:
      NODE_ENV: development
      DATABASE_URL: mongodb://db:27017/pick-a-nest-db
      DATABASE_NAME: pick-a-nest-db
      REDIS_URL: redis://redis:6379
      SECRET: ${SECRET}
      REFRESH_EXPIRES_IN: 30d
      ACCESS_EXPIRES_IN: 45m
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  redis:
    image: redis:8.8-m03-trixie
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    image: mongo:8.0.20
    ports:
      - 27017:27017
    volumes:
      - real_estate:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  real_estate:
